---
# - hosts: database

#   handlers:
#     - name: restart postgres
#       service:
#         name: postgresql
#         state: restarted
#       become: yes

#   tasks:

#     - name: Instalando postgresql server
#       apt: 
#         name: ['postgresql', 'python3-psycopg2']
#         state: latest
#       become: yes

#     - name: Configurando postgresql server
#       copy: 
#         src: "{{ item }}"
#         dest: "/etc/postgresql/10/main"
#       become: yes
#       with_items:
#         - "files/database/postgresql.conf"
#         - "files/database/pg_hba.conf"
#       notify: restart postgres

#     - name: Criando database keycloak
#       community.postgresql.postgresql_db:
#         name: "{{ dbname }}"
#       become: yes
#       become_user: postgres

#     - name: Criando usuario keycloak
#       community.postgresql.postgresql_user:
#         db: "{{ dbname }}"
#         name: "{{ dbuser }}"
#         password: "{{ dbpassword }}"
#         priv: ALL
#       become: yes
#       become_user: postgres
      
# - hosts: keycloak-server1
#   roles:
#     - keycloak

# - hosts: keycloak-server2
#   roles:
#     - keycloak

# - hosts: keycloak-server3
#   roles:
#     - keycloak

- hosts: reverse-proxy

  handlers:
    - name: reload nginx
      shell: nginx -s reload
      become: yes

  tasks:

    - name: Instalando NGINX
      apt: 
        name: ['nginx']
        state: latest
      become: yes

    - name: Copiando certificados
      copy: 
        src: "{{ item }}"
        dest: "/certificates/"
      become: yes
      with_items:
        - "files/nginx/certificates/keycloak_ccarj_key.crt"
        - "files/nginx/certificates/keycloak_ccarj_key.key"

    - name: Configurando NGINX
      copy: 
        src: "{{ item }}"
        dest: "/etc/nginx/conf.d/"
      become: yes
      with_items:
        - "files/nginx/lb.conf"
      notify: reload nginx
