---
- hosts: database

  handlers:
    - name: restart postgres
      shell: "/etc/init.d/postgresql restart"
      become: yes

  tasks:

    - name: "Instalando postgresql server"
      apt: 
        name: ['postgresql', 'python-psycopg2']
        state: latest
      become: yes

    - name: "Configurando postgresql server"
      copy: 
        src: "{{ item }}"
        dest: "/etc/postgresql/9.3/main"
      become: yes
      with_items:
        - "files/database/postgresql.conf"
        - "files/database/pg_hba.conf"
      notify: restart postgres

    - name: "Criando database keycloak"
      community.postgresql.postgresql_db:
        name: keycloak
      become: yes
      become_user: postgres

    - name: Connect to acme database, create django user, and grant access to database and products table
      community.postgresql.postgresql_user:
        db: keycloak
        name: keycloak
        password: keycloak
        priv: ALL
      become: yes
      become_user: postgres
      
- hosts: keycloak-servers
  tasks:
    - name: Adiciona repositorio para instalação do OpenJDK 11
      ansible.builtin.apt_repository:
        repo: ppa:openjdk-r/ppa
      become: yes

    - name: "Instalando postgresql server"
      apt: 
        name: ['openjdk-11-jdk']
        state: latest
        update_cache: yes
      become: yes